openapi: 3.0.0

info:
  title: Code Execution Service
  version: 1.0.0

definitions:
  CodeExecutionOutput:
    properties:
      stdin:
        type: string
        required: true
      expectedStdout:
        type: string
        required: true
      actualStdout:
        type: string
      isMatch:
        type: boolean
      status:
        type: string
      exception:
        type: string
        nullable: true
      stderr:
        type: string
        nullable: true
      executionTime:
        type: integer

components:
  schemas:
    CodeExecutionResponse:
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/definitions/CodeExecutionOutput"
    ErrorResponse:
      properties:
        message:
          type: string

paths:
  /:
    get:
      tags:
        - root
      summary: Root
      description: Ping the server
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server is running"

  /api/run:
    post:
      tags:
        - Code Execution
      summary: Execute Code
      description: Executes code in a specified language with given input and expected output.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  description: The programming language to execute the code in.
                  example: "python"
                code:
                  type: string
                  description: The source code to execute.
                  example: "name = input()\nage = input()\nprint('Hello ' + name + '. You are ' + age + ' years old this year?')\n\n"
                stdinList:
                  type: array
                  description: List of standard input values to pass to the code.
                  items:
                    type: string
                  example: ["Alice\n21", "Peter\n22"]
                stdoutList:
                  type: array
                  description: Expected standard output values to compare against.
                  items:
                    type: string
                  example:
                    [
                      "Hello Alice. You are 21 years old this year?\n",
                      "Hello Peter. You are 22 years old this year?\n",
                    ]
      responses:
        200:
          description: Execution Result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CodeExecutionResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
