services:
  user-service:
    image: peerprep/user-service
    build: ./backend/user-service
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ./backend/user-service/.env
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis
    networks:
      - peerprep-network
    volumes:
      - ./backend/user-service:/user-service
      - /user-service/node_modules
    restart: on-failure

  question-service:
    image: peerprep/question-service
    build: ./backend/question-service
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ./backend/question-service/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - user-service
    networks:
      - peerprep-network
    volumes:
      - ./backend/question-service:/question-service
      - /question-service/node_modules
    restart: on-failure

  matching-service:
    image: peerprep/matching-service
    build: ./backend/matching-service
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ./backend/matching-service/.env
    ports:
      - 3002:3002
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - peerprep-network
    volumes:
      - ./backend/matching-service:/matching-service
      - /matching-service/node_modules
    restart: on-failure

  frontend:
    image: peerprep/frontend
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5173:5173
    depends_on:
      - user-service
      - question-service
    networks:
      - peerprep-network
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    restart: on-failure

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - peerprep-network
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./backend/.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - peerprep-network
    depends_on:
      - mongo
    env_file: ./backend/.env

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - peerprep-network
    env_file: ./backend/matching-service/.env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10

  redis:
    image: redis:8.0-M01
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - peerprep-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 10s
      retries: 10
    command: ["redis-server"]

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - 5540:5540
    networks:
      - peerprep-network
    volumes:
      - redis-insight-data:/db
    depends_on:
      redis:
        condition: service_healthy
        restart: true

volumes:
  mongo-data:
  redis-data:
  redis-insight-data:

networks:
  peerprep-network:
    driver: bridge
