name: peerprep-test

services:
  test-user-service:
    image: peerprep/user-service
    build: ./backend/user-service
    env_file: ./backend/user-service/.env
    environment:
      - MONGO_URI_TEST=mongodb://mongo:mongo@test-mongo:27017/
    depends_on:
      - test-mongo
      - test-redis
    networks:
      - peerprep-network
    volumes:
      - ./backend/user-service:/user-service
      - /user-service/node_modules
    restart: on-failure
    command: ["npm", "test"]

  test-mongo:
    image: mongo
    restart: always
    networks:
      - peerprep-network
    env_file:
      - ./backend/.env

  test-redis:
    image: redis:8.0-M01
    container_name: test-redis
    networks:
      - peerprep-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 10s
      retries: 10
    command: ["redis-server"]

networks:
  peerprep-network:
    driver: bridge
