services:
  user-service:
    image: peerprep/user-service
    build: ./backend/user-service
    env_file: ./backend/user-service/.env
    ports:
      - 3001:3001
    networks:
      - peerprep-network
  question-service:
    image: peerprep/question-service
    build: ./backend/question-service
    env_file: ./backend/question-service/.env
    ports:
      - 3000:3000
    networks:
      - peerprep-network

networks:
  peerprep-network:
    driver: bridge
