openapi: 3.0.0

info:
  title: Question History Service
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    QnHistory:
      properties:
        userIds:
          type: array
          items:
            type: string
          description: User IDs
        questionId:
          type: string
          description: Question ID
        title:
          type: string
          description: Question title
        submissionStatus:
          type: string
          description: Code submission status
        dateAttempted:
          type: string
          format: date
          description: Date that question was attempted
        timeTaken:
          type: number
          description: Time taken for question attempt in seconds
        code:
          type: string
          description: Code submitted
        language:
          type: string
          description: Programming language used

definitions:
  QnHistory:
    type: object
    properties:
      _id:
        type: string
        description: Question history ID
      userIds:
        type: array
        items:
          type: string
        description: User IDs
      questionId:
        type: string
        description: Question ID
      title:
        type: string
        description: Question title
      submissionStatus:
        type: string
        description: Code submission status
      dateAttempted:
        type: string
        format: date
        description: Date that question was attempted
      timeTaken:
        type: number
        description: Time taken for question attempt in seconds
      code:
        type: string
        description: Code submitted
      language:
        type: string
        description: Programming language used
      createdAt:
        type: string
        description: Date of creation
      updatedAt:
        type: string
        description: Latest update
      __v:
        type: string
        description: Document version
  Error:
    type: object
    properties:
      message:
        type: string
        description: Message
  ServerError:
    type: object
    properties:
      message:
        type: string
        description: Message
      error:
        type: string
        description: Error

paths:
  /:
    get:
      tags:
        - root
      summary: Root
      description: Ping the server
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
  /api/qnhistories:
    post:
      tags:
        - qnhistories
      summary: Creates a question history
      description: Creates a question history
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QnHistory"
      responses:
        201:
          description: Created question history
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
                  qnHistory:
                    $ref: "#/definitions/QnHistory"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ServerError"
    get:
      tags:
        - qnhistories
      summary: Reads a list of question histories
      description: Reads a limited list of question histories based on current page and limit per page
      parameters:
        - in: query
          name: page
          type: integer
          required: true
          default: 1
          description: Page of question histories to return
        - in: query
          name: qnHistLimit
          type: integer
          required: true
          default: 10
          description: Limit on number of question histories to return
        - in: query
          name: userId
          type: string
          required: true
          description: User id of user to retrieve question histories
        - in: query
          name: title
          type: string
          required: false
          description: Search keywords for question history title
        - in: query
          name: status
          type: string
          required: false
          description: Filter for question history submission status
        - in: query
          name: order
          type: integer
          required: true
          description: Order (based on date attempted) to sort question history records by (1 for ascending and -1 for descending).
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
                  qnHistoryCount:
                    type: integer
                    description: Total number of question histories
                  qnHistories:
                    type: array
                    items:
                      $ref: "#/definitions/QnHistory"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ServerError"
  /api/qnhistories/{id}:
    put:
      tags:
        - qnhistories
      summary: Updates a question history
      description: Updates a question history
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Question history id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QnHistory"
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
                  qnHistory:
                    $ref: "#/definitions/QnHistory"
        404:
          description: Question History Not Found
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ServerError"
    get:
      tags:
        - qnhistories
      summary: Reads a question history
      description: Reads a question history
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Question history id
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
                  qnHistory:
                    $ref: "#/definitions/QnHistory"
        404:
          description: Question History Not Found
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ServerError"
