name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  secrets: write

env:
  NODE_VERSION: 20

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend/question-service, backend/user-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setting node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm install
      - name: Linting
        working-directory: ${{ matrix.service }}
        run: npm run lint
      - name: Tests
        working-directory: ${{ matrix.service }}
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: npm test