name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  NODE_VERSION: 20

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend/question-service, backend/user-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setting node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm install
      - name: Linting
        working-directory: ${{ matrix.service }}
        run: npm run lint
      - name: Set .env variables
        working-directory: ${{ matrix.service }}
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        run: |
          touch .env
          echo "FIREBASE_PROJECT_ID=${{ env.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_PRIVATE_KEY=${{ env.FIREBASE_PRIVATE_KEY }}" >> .env
          echo "FIREBASE_CLIENT_EMAIL=${{ env.FIREBASE_CLIENT_EMAIL }}" >> .env
      - name: Debug
        working-directory: ${{ matrix.service }}
        run: |
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
      - name: Tests
        working-directory: ${{ matrix.service }}
        run: npm test
