name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  NODE_VERSION: 20

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend/question-service, backend/user-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setting node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm install
      - name: Linting
        working-directory: ${{ matrix.service }}
        run: npm run lint
      # - name: Tests
      #   working-directory: ${{ matrix.service }}
      #   run: npm test
