name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint question service
        run: cd backend/question-service && npm install && npm run lint
      - name: Lint frontend
        run: cd frontend && npm install && npm run lint
